openapi: 3.0.0
info:
  title: Books API
  version: 1.0.0
  description: API documentation for the Books API
servers:
  - url: http://localhost:3000
paths:
  /books:
    post:
      summary: Create a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "Example Book Title"
                authors:
                  type: array
                  items:
                    type: string
                    description: Author ID
                    example: "660bcd300ccc4c51cfad084f"
                price:
                  type: number
                  format: float
                  example: 10.99
      responses:
        '201':
          description: Book created successfully
          content:
            application/json:
              schema:
                $ref: '#/src/schemas/Book'
        '400':
          description: Bad request
    get:
      summary: Get all books
      responses:
        '200':
          description: List of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        '500':
          description: Internal server error
  /books/{isbn}:
    get:
      summary: Get a book by ISBN
      parameters:
        - in: path
          name: isbn
          required: true
          description: ISBN of the book to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Book found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: Book not found
        '500':
          description: Internal server error
    patch:
      summary: Update a book by ISBN
      parameters:
        - in: path
          name: isbn
          required: true
          description: ISBN of the book to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '200':
          description: Book updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '400':
          description: Bad request
        '404':
          description: Book not found
        '500':
          description: Internal server error
    delete:
      summary: Delete a book by ISBN
      parameters:
        - in: path
          name: isbn
          required: true
          description: ISBN of the book to delete
          schema:
            type: string
      responses:
        '200':
          description: Book deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: Book not found
        '500':
          description: Internal server error
components:
  schemas:
    Book:
      type: object
      properties:
        title:
          type: string
        authors:
          type: array
          items:
            type: string
            description: Author ID
        price:
          type: number
          format: float
